language: java
jobs:
  include:
  - stage: test
    script: "./scripts/stage.sh unit-test"
env:
  global:
  - BINTRAY_USER=robvadai
  - secure: p3Ft3z9hQ2e08Or5k6LLcC4jKmFq08S/hdhWTkRY7TvNcjHjRK42f7xOKJliCJgLpUDOgMu6TT/qgV2oQsTpUVeDcPF3FOasbYj+8nGTLKHb4rYOf4WU3MmtbfwaZCXSr4Xw5SgPgxglOUPDzNF7TtABxpOKOYSHp+T6k7v7xI5dIHDjeyLaL/OXTmwqTkt2TfwBQsIuPIya+7w6xBwCvqT0Qgjj4FQq5k0e24maXkD3aQLbFd+mna/tJBfV700Zrelj8FdsZuJGVGxlX/UWfPTzIzNXBRPMuZCngs81maDTmNb69vx728R3vUMLvO/VAQxgCi/luZdOXzGa4OHTPVlAxubjIN+sP5c3Pm/tnhFhtE51IoiRsViuR7+POsY5Y9b9c9QNHfenljvQe/pdMz2qMSgmXEJTdqUWRpGU1U6XBJLDLLhOA0pAS4XSm7tyhE8iLhIZ6Wl7GdSbkVtlyFf7vyK8DsQLwFxxM9E14evCaBdVDUc4rq6d23VdcmYMBeUkvOpBugUTbpsUlp5hJbMTwTKYAmKZyUTHjxTE+ynA1KMnrHsnSo+jY45eDJGEzHWJi2J2qHxPuLP8qhfA5igwQSCwWjOTw4mQrbhCUZRDBCsgqeGM1Lm8aXPOmMvhG3+giWTRvkl3+eOcYo/kqywFLHmt+MQCkIF1UQZYZ6Y=
before_deploy:
  - git config --local user.name "Continuous Integration Automation"
  - git config --local user.email "ci@segence.com"
  - "./scripts/stage.sh generate-tag"
deploy:
  - provider: script
    script: "./scripts/stage.sh publish-to-bintray"
    on:
      branch: master
  - provider: releases
    api_key:
      secure: XmxK7PdqNItA3UiHMaw9NhyWQiw9u2MRgCj2vQnv6oC8sOoxBfI02wQEb1O2K/6HV5pXsSSz2sIIUmV4TA9U13rOOilEqQNR6Vn6ZQYsRbnsy3rHlig9kEUdzIev+4pAtw7Y0vKuhBo0LwaLwOxkay3tmiLxN0fxIo9LODLeZncnIJENxg35P5L65bQMQMG9fpxo310xmxqWcsZtX4Drb68/KrHN+d3s2hAh2XiCIYiuEqvvxDVIBlglMEfr1oHRfaeYZCsm9Ai8KN3VHSyE+cndeuMPmA+rENCAHTYkn/kcYDavRBV0Q/G8nNhf7RVJrgS3yCbBroCwe3KzIAxwtaEcdX5iqaqWDLY3y4IAqQfZnh1YVaFMGtCVBY2RmVpj1h0VOXtS/LOZwl02fmpzfDWi5vL5/Mf0XWJc12uA9KLL605BCQbn7sbbCHW+jGFAwsHKa4bL5AmrpDsnqKEI8ESIvHZD5hZbPIpSaHLMxmM9JltxmOeQUU9Rshnhy0aGQaV1BfvP1BfQay9MmDzgQn8o2rrM3Cc7ih+VZDC1HqjxbRECd20XG25Laf63guxpM3m7x0dGKbr/Pu0o2dxIooYSPJl9EpxSE/J8XWygAq8B67rpCIYQZDzB70halANkhFL7rLv/IICM5PyDvzP5KM2W8am9QLMetJFnEfWtiZ8=
    on:
      repo: Segence/kamon-jmx-collector
      branch: master
